const Admin={settings:null};
const adminDefaults={site_name:"Deepak Web Studio",hero_eyebrow:"WEB DESIGN • DEVELOPMENT • DIGITAL PRESENCE",hero_title:"Find a demo.|Build your website.",hero_text:"Explore ready-made website concepts for businesses, creators and professionals. Like one? Let's turn it into your own website.",hero_image:"",about_title:"Websites designed around your business.",about_text:"I create clean, responsive and conversion-focused websites for local businesses and personal brands.",about_image:"",about_label:"YOUR BUSINESS",whatsapp:"919999999999",whatsapp_message:"Hi, I want to build a website.",theme:"cream",accent:"#9a6a3a",accent2:"#d8b28a",background:"#f8f5ef",surface:"#fffdf9",build_title:"Let's build something that fits your business.",build_text:"Tell me what you need and I'll help you choose a suitable demo or create a custom design.",reviews_title:"What people say",meta_description:"Modern websites designed to help businesses attract customers.",features:["Modern responsive design","Clear calls-to-action","Easy future updates"]};
const $=id=>document.getElementById(id);
function msg(id,text){$(id).textContent=text;setTimeout(()=>$(id).textContent="",3500)}
function showDashboard(){ $("loginCard").classList.add("hidden");$("dashboard").classList.remove("hidden");$("logout").classList.remove("hidden");loadAdmin();}
async function login(e){e.preventDefault();if(!sb){msg("loginMsg","Supabase is not configured in config.js");return}const fd=new FormData(e.target);const r=await sb.auth.signInWithPassword({email:fd.get("email"),password:fd.get("password")});if(r.error)msg("loginMsg",r.error.message);else showDashboard();}
async function loadAdmin(){Admin.settings=await getSettings();fillSettings(Admin.settings);await loadSites();await loadReviews();}
function fillSettings(s){const f=$("settingsForm");Object.keys(s).forEach(k=>{const el=f.elements[k];if(el&&k!=="features")el.value=s[k]??""});renderFeatureInputs(s.features||adminDefaults.features);}
function renderFeatureInputs(arr){$("featureInputs").innerHTML="";(arr.length?arr:[""]).forEach((v,i)=>{const row=document.createElement("div");row.className="feature-input";row.innerHTML=`<input value="${esc(v)}" placeholder="Benefit ${i+1}"><button type="button" class="btn danger remove-feature">Remove</button>`;row.querySelector(".remove-feature").onclick=()=>{row.remove()};$("featureInputs").appendChild(row);});}
async function loadSites(){const sites=await getSites();$("siteList").innerHTML=sites.map(s=>`<div class="admin-item"><div class="admin-site"><img src="${esc(s.image_url||"")}" onerror="this.style.visibility='hidden'"><div><b>${esc(s.title)}</b><small>${esc(s.category)} · ${esc(s.demo_url)}</small></div></div><div class="admin-item-actions"><button class="btn ghost edit-site" data-id="${s.id}">Edit</button><button class="btn danger delete-site" data-id="${s.id}">Delete</button></div></div>`).join("")||"<p>No websites yet.</p>";
document.querySelectorAll(".edit-site").forEach(b=>b.onclick=()=>openSite(sites.find(x=>String(x.id)===String(b.dataset.id))));document.querySelectorAll(".delete-site").forEach(b=>b.onclick=()=>deleteSite(b.dataset.id));}
function openSite(s){$("siteForm").classList.remove("hidden");$("siteFormTitle").textContent=s?"Edit website":"Add website";const f=$("siteForm");["id","title","category","image_url","demo_url","description"].forEach(k=>f.elements[k].value=s?.[k]||"");f.elements.tags.value=(s?.tags||[]).join(",");window.scrollTo({top:$("siteForm").offsetTop-80,behavior:"smooth"});}
async function saveSite(e){e.preventDefault();if(!sb){msg("siteMsg","Configure Supabase first");return}const f=new FormData(e.target),payload={title:f.get("title"),category:f.get("category"),image_url:f.get("image_url"),demo_url:f.get("demo_url"),description:f.get("description"),tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean)};let r;if(f.get("id"))r=await sb.from("websites").update(payload).eq("id",f.get("id"));else r=await sb.from("websites").insert(payload);msg("siteMsg",r.error?r.error.message:"Saved successfully");if(!r.error){$("siteForm").classList.add("hidden");loadSites();}}
async function deleteSite(id){if(!confirm("Delete this website demo?"))return;const r=await sb.from("websites").delete().eq("id",id);if(r.error)alert(r.error.message);else loadSites();}
async function loadReviews(){if(!sb){$("adminFeedback").innerHTML="<p>Configure Supabase to moderate reviews.</p>";return}const r=await sb.from("feedback").select("*").order("created_at",{ascending:false});const data=r.data||[];$("adminFeedback").innerHTML=data.length?data.map(x=>`<div class="admin-item review-item"><div><b>${esc(x.name)} · ${"★".repeat(x.rating)}</b><p>${esc(x.message)}</p><small>${x.approved?"Published":"Waiting for approval"}</small></div><div class="admin-item-actions">${x.approved?`<button class="btn ghost unapprove" data-id="${x.id}">Hide</button>`:`<button class="btn primary approve" data-id="${x.id}">Approve</button>`}<button class="btn danger del-review" data-id="${x.id}">Delete</button></div></div>`).join(""):"<p>No reviews yet.</p>";
document.querySelectorAll(".approve,.unapprove").forEach(b=>b.onclick=async()=>{const approved=b.classList.contains("approve");await sb.from("feedback").update({approved}).eq("id",b.dataset.id);loadReviews();});document.querySelectorAll(".del-review").forEach(b=>b.onclick=async()=>{if(confirm("Delete this review?")){await sb.from("feedback").delete().eq("id",b.dataset.id);loadReviews();}});
}
async function saveSettings(e){e.preventDefault();if(!sb){msg("settingsMsg","Configure Supabase first");return}const f=new FormData(e.target),features=[...document.querySelectorAll("#featureInputs input")].map(x=>x.value.trim()).filter(Boolean),payload={};["site_name","hero_eyebrow","hero_title","hero_text","hero_image","about_title","about_text","about_image","about_label","whatsapp","whatsapp_message","build_title","build_text","reviews_title","meta_description","theme","accent","accent2","background"].forEach(k=>payload[k]=f.get(k));payload.features=features;payload.surface=Admin.settings?.surface||"#fffdf9";const r=await sb.from("settings").upsert({id:1,...payload});msg("settingsMsg",r.error?r.error.message:"All settings saved");if(!r.error){Admin.settings={...Admin.settings,...payload};}}
function tabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.add("hidden"));b.classList.add("active");$("tab-"+b.dataset.tab).classList.remove("hidden");});}
async function initAdmin(){tabs();$("loginForm").addEventListener("submit",login);$("logout").onclick=async()=>{if(sb)await sb.auth.signOut();location.reload()};$("newSite").onclick=()=>openSite();$("cancelSite").onclick=()=>$("siteForm").classList.add("hidden");$("siteForm").addEventListener("submit",saveSite);$("settingsForm").addEventListener("submit",saveSettings);$("addFeature").onclick=()=>renderFeatureInputs([...document.querySelectorAll("#featureInputs input")].map(x=>x.value).concat([""]));
if(sb){const r=await sb.auth.getSession();if(r.data.session)showDashboard();sb.auth.onAuthStateChange((_e,session)=>{if(session)showDashboard();});}}
if($("loginForm"))initAdmin();
